//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Shiba Project/Input/Controller.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controller : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controller()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controller"",
    ""maps"": [
        {
            ""name"": ""PetController"",
            ""id"": ""3b3b78a3-36dc-4891-97c4-b223c69ab5f7"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""51b156f0-c5c7-4657-90e7-80bd1bd95fe8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e77510b2-58b5-406d-ac2b-d54787d128cf"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PetController
        m_PetController = asset.FindActionMap("PetController", throwIfNotFound: true);
        m_PetController_Click = m_PetController.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PetController
    private readonly InputActionMap m_PetController;
    private IPetControllerActions m_PetControllerActionsCallbackInterface;
    private readonly InputAction m_PetController_Click;
    public struct PetControllerActions
    {
        private @Controller m_Wrapper;
        public PetControllerActions(@Controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_PetController_Click;
        public InputActionMap Get() { return m_Wrapper.m_PetController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PetControllerActions set) { return set.Get(); }
        public void SetCallbacks(IPetControllerActions instance)
        {
            if (m_Wrapper.m_PetControllerActionsCallbackInterface != null)
            {
                @Click.started -= m_Wrapper.m_PetControllerActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_PetControllerActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_PetControllerActionsCallbackInterface.OnClick;
            }
            m_Wrapper.m_PetControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
            }
        }
    }
    public PetControllerActions @PetController => new PetControllerActions(this);
    public interface IPetControllerActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
}
